// <auto-generated />
using Hospital.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Hospital.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20180310051344_salary")]
    partial class salary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hospital.Modules.Doctors_Profile.Models.LabReportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DoctorName");

                    b.Property<string>("DoctorStatus");

                    b.Property<string>("LabStatus");

                    b.Property<string>("LabType");

                    b.Property<string>("SpecialistName");

                    b.Property<DateTime>("date");

                    b.Property<string>("description");

                    b.Property<int>("labNo");

                    b.Property<int>("nicNo");

                    b.Property<string>("patientName");

                    b.HasKey("Id");

                    b.ToTable("LabReportRequest");
                });

            modelBuilder.Entity("Hospital.Modules.Doctors_Profile.Models.RequestFacility", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Department");

                    b.Property<string>("Description");

                    b.Property<string>("DoctorName");

                    b.Property<string>("Topic");

                    b.HasKey("Id");

                    b.ToTable("RequestFacility");
                });

            modelBuilder.Entity("Hospital.Modules.DrugDetails.Models.Drug", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("Qty");

                    b.Property<string>("State");

                    b.HasKey("ID");

                    b.ToTable("Drug");
                });

            modelBuilder.Entity("Hospital.Modules.SalaryDetails.Model.SalaryDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NIC");

                    b.Property<double>("Rating");

                    b.Property<double>("WorkingHrs");

                    b.HasKey("ID");

                    b.ToTable("SalaryDetails");
                });

            modelBuilder.Entity("Hospital.Modules.StaffManagement.Models.LogInDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Position");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("LogInDetails");
                });

            modelBuilder.Entity("Hospital.Modules.StaffManagement.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Topic");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Reminder");
                });
#pragma warning restore 612, 618
        }
    }
}
